version: '3.8'

services:
  test:
    container_name: geospatial-data-converter-test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./tests/:/home/appuser/tests/
      - ./pyproject.toml:/home/appuser/pyproject.toml
    working_dir: /home/appuser
    command: ["pytest"]

  geospatial-data-converter:
    container_name: geospatial-data-converter
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    depends_on:
      test:
        condition: service_completed_successfully
    ports:
      - "${APP_PORT:-7860}:${APP_PORT:-7860}"
