[tool.pytest.ini_options]
pythonpath = ["geospatial-data-converter"]
testpaths = ["tests"]
addopts = "--cov=geospatial-data-converter"

[tool.bumpver]
current_version = "1.0.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]
"geospatial-data-converter/app.py" = ['__version__ = "{version}"']
"kubernetes/resources.yaml" = ['        image: joshuasundance/geospatial-data-converter:{version}']
